// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWkoZyPM1dPgEeDeYf8J0J4mhl6je-T8',
    appId: '1:713383386628:web:4cda23a7f5e99264aa9f51',
    messagingSenderId: '713383386628',
    projectId: 'aboutsection-d476c',
    authDomain: 'aboutsection-d476c.firebaseapp.com',
    storageBucket: 'aboutsection-d476c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjYnj9Bnt-whqPZX4JZqJ_rEJAJoCWWM',
    appId: '1:713383386628:android:0a86fd5f85da99f7aa9f51',
    messagingSenderId: '713383386628',
    projectId: 'aboutsection-d476c',
    storageBucket: 'aboutsection-d476c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXe1AqYb83TvcPImaH-NY5zFb46oBvDik',
    appId: '1:713383386628:ios:e4a6a6c565787260aa9f51',
    messagingSenderId: '713383386628',
    projectId: 'aboutsection-d476c',
    storageBucket: 'aboutsection-d476c.appspot.com',
    iosClientId: '713383386628-lut6dam6btqu23b84kdg0t9a5ms81sk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileSection',
  );
}
